apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: development
  owner: guest
  definition: |
    openapi: "3.0.4"
    info:
      title: "My Backstage API"
      description: "A REST API integrated with Backstage and NSwag."
      version: "v1"
    paths:
      /WeatherForecast:
        get:
          tags:
            - "WeatherForecast"
          responses:
            "200":
              description: "OK"
              content:
                text/plain:
                  schema:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/WeatherForecast"
                application/json:
                  schema:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/WeatherForecast"
                text/json:
                  schema:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/WeatherForecast"
    components:
      schemas:
        WeatherForecast:
          type: "object"
          properties:
            date:
              type: "string"
              format: "date-time"
            temperatureC:
              type: "integer"
              format: "int32"
            temperatureF:
              type: "integer"
              format: "int32"
              readOnly: true
            summary:
              type: "string"
              nullable: true
          additionalProperties: false
