apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
  annotations:
    backstage.io/swagger-ui:
      $text: ./swagger.json
spec:
  type: openapi
  lifecycle: development
  owner: guest
  definition:
    $text: ./swagger.json
