apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: development
  owner: team-dev
  definition: https://localhost:7293/swagger/v1/swagger.json
    #$text: https://localhost:7293/swagger/v1/swagger.json
    #$text: http://localhost:5036/swagger/v1/swagger.json
  version: 3.0.0
