apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: team-a-api-v1
  description: Version 1 of the API for Team A
spec:
  type: openapi
  lifecycle: development
  owner: guest
  definition:
    $text: ./apis/WeatherForecastAPI.json


