apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: development
  owner: team-dev
  definition:
    raw: |
      {
        "swagger": "2.0",
        "info": {
          "title": "My API",
          "version": "1.0.0"
        },
        "paths": {
          "/myendpoint": {
            "get": {
              "summary": "My endpoint"
            }
          }
        }
      }
