apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
  annotations:
    backstage.io/swagger-ui: http://127.0.0.1:5036/swagger/v1/swagger.json  # <- Swagger UI funcionando
spec:
  type: openapi
  lifecycle: development
  owner: guest
  definition: http://localhost:5036/swagger/v1/swagger.json  
