apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: A REST API with Swashbuckle and NSwag.
  tags:
    - rest
    - csharp
spec:
  type: openapi
  lifecycle: development
  owner: team-dev
  #definition: https://localhost:7293/swagger/v1/swagger.json
  definition:
    schema: https://swagger.io/specification/v2/schema.json
    swagger: "2.0"
    url: https://localhost:7293/swagger/v1/swagger.json
  version: 3.0.0
