apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-backstage-api
  description: Version 2 of the API
spec:
  type: openapi
  lifecycle: development
  owner: guest
  definition:
    $text: ./apis/WeatherForecastAPI.json


