site_name: My Backstage API Docs
nav:
  - Getting Started: docs/getting-started.md
repo_url: https://github.com/p17edro/MyBackstageAPI
edit_uri: edit/main/apis/subsystem-beta/service-or-component/docs
