site_name: My Backstage API Docs
docs_dir: docs
nav:
  - Home: index.md 
  - Getting Started: getting-started.md
repo_url: https://github.com/p17edro/MyBackstageAPI
edit_uri: edit/main/apis/subsystem-beta/service-or-component/docs